name: Matrix Output Example

on: push

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate Output
        id: output_step
        run: echo "RESULT=Node.js ${{ matrix.node-version }} tested" >> $GITHUB_ENV

      - name: Save Output
        id: save_output
        run: echo "::set-output name=test_result::Node.js ${{ matrix.node-version }} tested"

    outputs:
      test_result: ${{ steps.save_output.outputs.test_result }}  # Store output

  collect-output:
    runs-on: ubuntu-latest
    needs: matrix-job  # Wait for the matrix job to finish

    steps:
      - name: Print Output
        run: echo "Matrix Job Output: ${{ needs.matrix-job.outputs.test_result }}"
